groups: []
resources:
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent
- name: gcs-source-json
  type: gcs
  source:
    bucket: kubo-pipeline-store
    json_key: ((gcs-json-key))
    versioned_file: source.json
- name: cfcr-deployment
  type: bosh-deployment
  source:
    deployment: ci-service
- name: gcs-load-balancer-vars
  type: gcs
  source:
    bucket: kubo-pipeline-store
    json_key: ((gcs-json-key))
    versioned_file: load-balancer-vars.yml
- name: run-apply-addons-errand
  type: bosh-errand
  source:
    deployment: ci-service
- name: run-smoke-tests-errand
  type: bosh-errand
  source:
    deployment: ci-service
- name: kubo-lock-gcp-lb
  type: pool
  source:
    branch: master
    pool: kubo-gcp-lb
    private_key: ((git-ssh-key.private_key))
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
- name: gcs-bosh-state
  type: gcs
  source:
    bucket: kubo-pipeline-store
    json_key: ((gcs-json-key))
    versioned_file: bosh/state.json
- name: kubo-dev-release
  type: gcs
  source:
    bucket: kubo-public
    json_key: ((gcs-json-key))
    versioned_file: kubo-release-latest.tgz
- name: slackers
  type: git
  source:
    paths:
    - slackers
    private_key: ((git-ssh-key.private_key))
    uri: git@github.com:cloudfoundry-incubator/cfcr-home.git
- name: kubo-dev-deployment
  type: gcs
  source:
    bucket: kubo-public
    json_key: ((gcs-json-key))
    versioned_file: kubo-deployment-latest.tgz
- name: gcs-bosh-creds
  type: gcs
  source:
    bucket: kubo-pipeline-store
    json_key: ((gcs-json-key))
    versioned_file: bosh/creds.yml
- name: git-kubo-ci
  type: git
  source:
    branch: master
    private_key: ((git-ssh-key.private_key))
    uri: git@github.com:pivotal-cf-experimental/kubo-ci.git
- name: slack-alert
  type: slack-notification
  source:
    url: ((build-alert-slack-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: v2.11.1-rc.4
- name: bosh-errand
  type: docker-image
  source:
    repository: cfcommunity/bosh2-errand-resource
jobs:
- name: claim-lock-gcp-lb
  plan:
  - get: kubo-dev-release
    trigger: true
  - put: kubo-lock-gcp-lb
    params:
      acquire: true
- name: install-bosh-gcp-lb
  plan:
  - aggregate:
    - get: kubo-dev-release
      passed:
      - claim-lock-gcp-lb
    - get: git-kubo-ci
    - get: kubo-dev-deployment
    - get: kubo-lock-gcp-lb
      passed:
      - claim-lock-gcp-lb
      trigger: true
      version: every
  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    input_mapping:
      gcs-kubo-deployment-pre: kubo-dev-deployment
  - task: install
    file: git-kubo-ci/tasks/install-bosh.yml
    params:
      CLOUD_CONFIG_OPS_FILE: gcp-lb-k8s-cloud-config-multiaz.yml
      USE_TURBULENCE: 1
    input_mapping:
      kubo-lock: kubo-lock-gcp-lb
    tags:
    - gcp-lb
  - aggregate:
    - put: gcs-bosh-creds
      params:
        file: bosh-creds/creds.yml
    - put: gcs-bosh-state
      params:
        file: bosh-state/state.json
  - task: generate-load-balancer-vars
    file: git-kubo-ci/tasks/generate-load-balancer-vars.yml
    input_mapping:
      kubo-lock: kubo-lock-gcp-lb
  - task: generate-source-json
    file: git-kubo-ci/tasks/generate-source-json.yml
    input_mapping:
      kubo-lock: kubo-lock-gcp-lb
  - aggregate:
    - put: gcs-load-balancer-vars
      params:
        file: load-balancer-vars/vars.yml
    - put: gcs-source-json
      params:
        file: source-json/source.json
- name: deploy-k8s-gcp-lb
  plan:
  - aggregate:
    - get: kubo-dev-release
      passed:
      - install-bosh-gcp-lb
    - get: git-kubo-ci
    - get: kubo-lock-gcp-lb
      passed:
      - install-bosh-gcp-lb
      trigger: true
      version: every
    - get: kubo-dev-deployment
      passed:
      - install-bosh-gcp-lb
    - get: gcs-bosh-state
      passed:
      - install-bosh-gcp-lb
    - get: gcs-bosh-creds
      passed:
      - install-bosh-gcp-lb
    - get: gcs-source-json
      passed:
      - install-bosh-gcp-lb
    - get: gcs-load-balancer-vars
      passed:
      - install-bosh-gcp-lb
    - get: stemcell
  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    input_mapping:
      gcs-kubo-deployment-pre: kubo-dev-deployment
  - put: cfcr-deployment
    params:
      cleanup: true
      manifest: git-kubo-deployment/manifests/cfcr.yml
      ops_files:
      - git-kubo-deployment/manifests/ops-files/misc/single-master.yml
      - git-kubo-deployment/manifests/ops-files/misc/bootstrap.yml
      - git-kubo-deployment/manifests/ops-files/use-runtime-config-bosh-dns.yml
      - git-kubo-deployment/manifests/ops-files/allow-privileged-containers.yml
      - git-kubo-ci/manifests/ops-files/allow-security-context.yml
      - git-kubo-deployment/manifests/ops-files/disable-deny-escalating-exec.yml
      - git-kubo-deployment/manifests/ops-files/iaas/gcp/cloud-provider.yml
      - git-kubo-deployment/manifests/ops-files/iaas/gcp/add-subnetwork-for-internal-load-balancer.yml
      releases:
      - kubo-dev-release/kubo-release-latest.tgz
      source_file: gcs-source-json/source.json
      stemcells:
      - stemcell/stemcell.tgz
      vars:
        deployment_name: ci-service
        worker_count: 3
      vars_files:
      - gcs-load-balancer-vars/load-balancer-vars.yml
      - kubo-lock-gcp-lb/metadata
    tags:
    - gcp-lb
  - put: run-apply-addons-errand
    params:
      keep_alive: true
      name: apply-addons
      source_file: gcs-source-json/source.json
    tags:
    - gcp-lb
  - put: run-smoke-tests-errand
    params:
      keep_alive: true
      name: smoke-tests
      source_file: gcs-source-json/source.json
    tags:
    - gcp-lb
- name: run-istio-tests
  serial: true
  plan:
  - aggregate:
    - get: slackers
    - get: kubo-dev-release
      passed:
      - deploy-k8s-gcp-lb
    - get: git-kubo-ci
    - get: kubo-dev-deployment
      passed:
      - deploy-k8s-gcp-lb
    - get: kubo-lock
      passed:
      - deploy-k8s-gcp-lb
      trigger: true
      resource: kubo-lock-gcp-lb
      version: every
    - get: gcs-bosh-creds
      passed:
      - deploy-k8s-gcp-lb
    - get: gcs-bosh-state
      passed:
      - deploy-k8s-gcp-lb
    - get: gcs-source-json
      passed:
      - deploy-k8s-gcp-lb
  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    input_mapping:
      gcs-kubo-deployment-pre: kubo-dev-deployment
  - task: run-istio-tests
    file: git-kubo-ci/tasks/run-istio-tests.yml
    on_failure: &on_failure
      do:
      - task: configure-slack-notification
        file: git-kubo-ci/tasks/configure-slack-notification-without-git-release.yml
      - put: slack-alert
        params:
          attachments_file: slack-notification/attachments
          text: |
            Build Failed. https://ci.kubo.sh/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    attempts: 2
- name: destroy-k8s
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: slackers
    - get: kubo-lock
      passed:
      - run-istio-tests
      trigger: true
      resource: kubo-lock-gcp-lb
      version: every
    - get: kubo-dev-deployment
      passed:
      - run-istio-tests
    - get: kubo-dev-release
      passed:
      - run-istio-tests
    - get: gcs-bosh-creds
      passed:
      - run-istio-tests
    - get: gcs-bosh-state
      passed:
      - run-istio-tests
    - get: gcs-source-json
      passed:
      - run-istio-tests
  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    input_mapping:
      gcs-kubo-deployment-pre: kubo-dev-deployment
  - task: destroy-k8s
    file: git-kubo-ci/tasks/destroy-k8s-instance.yml
    input_mapping:
      kubo-lock: kubo-lock
    on_failure: *on_failure
- name: destroy-bosh
  plan:
  - aggregate:
    - get: slackers
    - get: git-kubo-ci
    - get: kubo-dev-deployment
      passed:
      - destroy-k8s
    - get: kubo-dev-release
      passed:
      - destroy-k8s
    - get: kubo-lock
      passed:
      - destroy-k8s
      trigger: true
      resource: kubo-lock-gcp-lb
      version: every
    - get: gcs-bosh-creds
      passed:
      - destroy-k8s
    - get: gcs-bosh-state
      passed:
      - destroy-k8s
  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
    input_mapping:
      gcs-kubo-deployment-pre: kubo-dev-deployment
  - task: destroy
    file: git-kubo-ci/tasks/destroy-bosh.yml
    input_mapping:
      kubo-lock: kubo-lock
    on_failure: *on_failure
  - put: kubo-lock
    resource: kubo-lock-gcp-lb
    params:
      release: kubo-lock
