platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/create-final-release.sh
inputs:
  - name: git-kubo-ci
  - name: kubo-version
  - name: git-kubo-release-master
outputs:
  - name: kubo-release-tarball
  - name: git-kubo-release-master-output
params:
  ACCESS_KEY_ID:
  SECRET_ACCESS_KEY:
