platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-bbr-tests.sh

params:
  DEPLOYMENT_NAME: ci-service

inputs:
  - name: git-kubo-ci
  - name: source-json
  - name: gcs-kubeconfig
  - name: bbr-cli
