platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
inputs:
- name: git-kubo-ci
- name: kubo-lock
- name: gcs-bosh-creds
outputs:
- name: kubeconfig
params:
  DEPLOYMENT_NAME: "ci-service"
  CREDFILE: bosh-creds/creds.yml
  VARFILE: kubo-lock/metadata
  KUBECONFIG: kubeconfig/config

run:
  path: git-kubo-ci/scripts/set_kubeconfig
